### ISSUE TITLE
Bump webpack-bundle-analyzer dependency to support v3

### ISSUE THREAD

**Issue by feimosi** [byzyk/react-app-rewire-webpack-bundle-analyzer#1]
Could you update the dependency version to support the newest `webpack-bundle-analyzer`? I'm using it without any problems in my project. Cheers.

**Comment by byzyk** [comment]
@feimosi released in `1.1.0`. Let me know if it works well for you 🙂

**Comment by feimosi** [comment]
Works perfectly fine, thanks :slightly_smiling_face:
